### ISSUE TITLE
mod_log_failure.c:25:10: fatal error: mod_log.h: No such file or directory

### ISSUE THREAD

**Issue by Mimikoo** [Castaglia/proftpd-mod_log_failure#2]
mod_log_failure.c:25:10: fatal error: mod_log.h: No such file or directory
   25 | #include "mod_log.h"

**Comment by Castaglia** [comment]
How exactly are you encountering this error?  What are the commands you are running?

**Comment by Castaglia** [comment]
This should now be fixed in master.  *Note*, however, this module is incomplete, and is not expected to function at all.
